# Generated by Django 4.0.5 on 2022-06-13 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='fecha_publicacion',
        ),
        migrations.AlterField(
            model_name='producto',
            name='valor',
            field=models.IntegerField(default=5000),
        ),
    ]
