# Generated by Django 4.0.5 on 2022-06-14 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_contacto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contacto',
            name='avisos',
        ),
        migrations.AddField(
            model_name='producto',
            name='cantidad',
            field=models.IntegerField(default=5),
        ),
        migrations.AlterField(
            model_name='producto',
            name='valor',
            field=models.IntegerField(),
        ),
    ]
