# Generated by Django 4.0.5 on 2022-06-14 05:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_contacto_avisos_producto_cantidad_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='producto',
            old_name='cantidad',
            new_name='stock',
        ),
    ]
